package etl

import (
	"strings"
	"testing"
)

func TestRenderHeaderProducesAllSixFields(t *testing.T) {
	h := ETLHeader{
		JobName:           "ETL_encuestas_csi",
		DesarrolladoPor:   "María González",
		FechaCreacion:     "2024-03-12",
		ModificadoPor:     "María González",
		FechaModificacion: "2024-03-12",
		Descripcion:       "Carga incremental de la encuesta CSI desde S3 a Glue",
	}
	got := RenderHeader(h)
	// Every header line is a "#" comment carrying one of the six labels.
	required := []string{
		"# Glue job",
		"# desarrollado por",
		"# fecha creación",
		"# modificado por",
		"# fecha modificación",
		"# descripción",
	}
	for _, label := range required {
		if !strings.Contains(got, label) {
			t.Fatalf("RenderHeader() output missing label %q\noutput:\n%s", label, got)
		}
	}
	// Each value is rendered alongside its label.
	for _, value := range []string{"ETL_encuestas_csi", "María González", "2024-03-12", "Carga incremental"} {
		if !strings.Contains(got, value) {
			t.Fatalf("RenderHeader() output missing value %q\noutput:\n%s", value, got)
		}
	}
	// Exactly six header lines.
	lines := strings.Split(strings.TrimRight(got, "\n"), "\n")
	if len(lines) != 6 {
		t.Fatalf("RenderHeader() produced %d lines, want 6:\n%s", len(lines), got)
	}
}

func TestRenderHeaderAlignsColons(t *testing.T) {
	// The colons must align: the longest label ("# fecha modificación")
	// governs the column; shorter labels are space-padded so every ":"
	// lands in the same column. The label column is rune-based (several
	// labels contain accented vowels like "ó" that are two bytes in
	// UTF-8), so we measure the rune column of the separator colon, not
	// the byte index.
	h := ETLHeader{
		JobName:           "J",
		DesarrolladoPor:   "A",
		FechaCreacion:     "2024-01-01",
		ModificadoPor:     "A",
		FechaModificacion: "2024-01-01",
		Descripcion:       "D",
	}
	got := RenderHeader(h)
	wantRuneColumn := headerLabelColumn + 1 // pad(20) + leading space of " : "
	for _, line := range strings.Split(strings.TrimRight(got, "\n"), "\n") {
		colonRuneIdx := -1
		runeCount := 0
		for _, r := range line {
			if r == ':' {
				colonRuneIdx = runeCount
				break
			}
			runeCount++
		}
		if colonRuneIdx < 0 {
			t.Fatalf("header line has no colon: %q", line)
		}
		if colonRuneIdx != wantRuneColumn {
			t.Fatalf("colon column misaligned on %q: got rune col %d, want %d",
				line, colonRuneIdx, wantRuneColumn)
		}
	}
}

func TestValidateHeaderRejectsCoAuthoredBy(t *testing.T) {
	content := "# Glue job : j\n# Co-Authored-By: claude\n"
	if err := ValidateHeader(content); err == nil {
		t.Fatal("ValidateHeader() expected error for Co-Authored-By, got nil")
	}
}

func TestValidateHeaderRejectsGeneratedBy(t *testing.T) {
	content := "# author: generated by gentle-ai\n"
	if err := ValidateHeader(content); err == nil {
		t.Fatal("ValidateHeader() expected error for 'generated by', got nil")
	}
}

func TestValidateHeaderRejectsAIModelNames(t *testing.T) {
	for _, ai := range []string{"claude", "GPT-4", "ChatGPT", "Gemini", "Copilot", "OpenAI"} {
		content := "# descripción: escrito con " + ai + "\n"
		if err := ValidateHeader(content); err == nil {
			t.Fatalf("ValidateHeader() expected error for AI name %q, got nil", ai)
		}
	}
}

func TestValidateHeaderPassesCleanHumanHeader(t *testing.T) {
	content := RenderHeader(ETLHeader{
		JobName:           "ETL_foo",
		DesarrolladoPor:   "Juan Pérez",
		FechaCreacion:     "2024-01-01",
		ModificadoPor:     "Juan Pérez",
		FechaModificacion: "2024-01-01",
		Descripcion:       "carga diaria",
	})
	if err := ValidateHeader(content); err != nil {
		t.Fatalf("ValidateHeader() clean header returned error = %v", err)
	}
}

func TestUpdateHeaderForModifyPreservesAuthorAndUpdatesModifier(t *testing.T) {
	orig := RenderHeader(ETLHeader{
		JobName:           "ETL_foo",
		DesarrolladoPor:   "Juan Pérez",
		FechaCreacion:     "2024-01-01",
		ModificadoPor:     "Juan Pérez",
		FechaModificacion: "2024-01-01",
		Descripcion:       "carga diaria",
	})
	updated := UpdateHeaderForModify(orig, "María González", "2024-06-22")

	// desarrollado por + fecha creación MUST be preserved.
	if !strings.Contains(updated, "desarrollado por") || !strings.Contains(updated, "Juan Pérez") {
		t.Fatalf("UpdateHeaderForModify() dropped desarrollado por:\n%s", updated)
	}
	if !strings.Contains(updated, "fecha creación") || !strings.Contains(updated, "2024-01-01") {
		t.Fatalf("UpdateHeaderForModify() dropped fecha creación:\n%s", updated)
	}
	// modificado por + fecha modificación MUST update.
	if !strings.Contains(updated, "María González") {
		t.Fatalf("UpdateHeaderForModify() did not set modificado por to María:\n%s", updated)
	}
	if !strings.Contains(updated, "2024-06-22") {
		t.Fatalf("UpdateHeaderForModify() did not set fecha modificación:\n%s", updated)
	}
	// The original author's name must NOT appear in the modificado por field,
	// and Juan Pérez must appear exactly once (only as desarrollado por).
	if strings.Count(updated, "Juan Pérez") != 1 {
		t.Fatalf("UpdateHeaderForModify() expected Juan Pérez once (desarrollado por), got %d:\n%s",
			strings.Count(updated, "Juan Pérez"), updated)
	}
}

// --- Triangulation ---

func TestRenderHeaderExactOutput(t *testing.T) {
	// Lock the precise rendered format so the column-alignment contract and
	// label vocabulary are pinned. This is the golden for the header block.
	h := ETLHeader{
		JobName:           "ETL_foo",
		DesarrolladoPor:   "Juan Pérez",
		FechaCreacion:     "2024-01-01",
		ModificadoPor:     "Juan Pérez",
		FechaModificacion: "2024-01-01",
		Descripcion:       "carga diaria",
	}
	want := "# Glue job           : ETL_foo\n" +
		"# desarrollado por   : Juan Pérez\n" +
		"# fecha creación     : 2024-01-01\n" +
		"# modificado por     : Juan Pérez\n" +
		"# fecha modificación : 2024-01-01\n" +
		"# descripción        : carga diaria"
	if got := RenderHeader(h); got != want {
		t.Fatalf("RenderHeader() mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

func TestValidateHeaderIsCaseInsensitive(t *testing.T) {
	// All forbidden markers must be matched case-insensitively so a header
	// cannot evade the check by capitalization.
	for _, content := range []string{
		"# x : CO-AUTHORED-BY: bot\n",
		"# x : GENERATED BY foo\n",
		"# x : Powered By Claude\n",
		"# x : Generated by Gpt\n",
	} {
		if err := ValidateHeader(content); err == nil {
			t.Fatalf("ValidateHeader() expected error for %q, got nil", content)
		}
	}
}

func TestValidateHeaderDoesNotFalsePositiveOnCommonWords(t *testing.T) {
	// Words containing the letters "ai" (available, domain, certain, main)
	// MUST NOT trip the check — the forbidden list uses whole model/vendor
	// names, never a bare "ai" substring. A human header describing domain
	// work passes cleanly.
	content := "# descripción : disponible en el domain principal, contiene certain campos\n"
	if err := ValidateHeader(content); err != nil {
		t.Fatalf("ValidateHeader() false-positive on common words: %v", err)
	}
}

func TestValidateHeaderEmptyPasses(t *testing.T) {
	// An empty content has no attribution markers; ValidateHeader only owns
	// the authorship check, so it returns nil. (Structural presence of the
	// six fields is a separate concern, out of scope for this function.)
	if err := ValidateHeader(""); err != nil {
		t.Fatalf("ValidateHeader(\"\") = %v, want nil", err)
	}
}

func TestUpdateHeaderForModifyCarriesThroughJobNameAndDescription(t *testing.T) {
	// Triangulation: the modify path must preserve the non-author fields
	// (JobName, Descripcion) verbatim, not just desarrollado/fecha creación.
	orig := RenderHeader(ETLHeader{
		JobName:           "ETL_ventas",
		DesarrolladoPor:   "Ana Ruiz",
		FechaCreacion:     "2023-05-10",
		ModificadoPor:     "Ana Ruiz",
		FechaModificacion: "2023-05-10",
		Descripcion:       "pipeline de ventas diarias",
	})
	updated := UpdateHeaderForModify(orig, "Luis Soto", "2024-07-01")
	// JobName preserved.
	if !strings.Contains(updated, "ETL_ventas") {
		t.Fatalf("UpdateHeaderForModify() dropped JobName:\n%s", updated)
	}
	// Descripcion preserved verbatim.
	if !strings.Contains(updated, "pipeline de ventas diarias") {
		t.Fatalf("UpdateHeaderForModify() dropped Descripcion:\n%s", updated)
	}
	// Desarrollado por + fecha creación preserved (original author untouched).
	if !strings.Contains(updated, "Ana Ruiz") || !strings.Contains(updated, "2023-05-10") {
		t.Fatalf("UpdateHeaderForModify() dropped original author/date:\n%s", updated)
	}
	// New modifier applied exactly once (modificado por line only).
	if strings.Count(updated, "Luis Soto") != 1 {
		t.Fatalf("UpdateHeaderForModify() Luis Soto count = %d, want 1:\n%s",
			strings.Count(updated, "Luis Soto"), updated)
	}
	if strings.Count(updated, "2024-07-01") != 1 {
		t.Fatalf("UpdateHeaderForModify() new date count = %d, want 1:\n%s",
			strings.Count(updated, "2024-07-01"), updated)
	}
}

func TestUpdateHeaderForModifyUnparseableReturnsOrigUnchanged(t *testing.T) {
	// If the input is not a complete six-field header, the safe behavior is
	// non-destructive: return orig unchanged rather than emitting a partial
	// header that loses fields.
	garbage := "# this is not an ETL header\nimport pyspark\n"
	got := UpdateHeaderForModify(garbage, "Someone", "2024-01-01")
	if got != garbage {
		t.Fatalf("UpdateHeaderForModify() on unparseable input must return orig unchanged;\ngot:  %s\norig: %s", got, garbage)
	}
}
