package etl

import (
	"fmt"
	"strings"
	"unicode/utf8"
)

// ETLHeader is the six-field authorship header every generated or modified
// `.py` ETL file MUST carry. The fields mirror the header protocol required
// by the data-engineering domain spec: the Glue job name, the original
// author (desarrollado por) and creation date, the last modifier and
// modification date, and a free-form description.
type ETLHeader struct {
	JobName           string
	DesarrolladoPor   string
	FechaCreacion     string
	ModificadoPor     string
	FechaModificacion string
	Descripcion       string
}

// headerLabelColumn is the rune width every "# <label>" prefix is padded to
// before the " : " separator. It is governed by the longest label
// ("# fecha modificación" = 20 runes), so shorter labels are space-padded
// and every colon lands in the same column.
const headerLabelColumn = 20

// headerLabels is the fixed ordered list of (label, field) pairs rendered by
// RenderHeader. Order is part of the contract: a reader scanning a header
// relies on the six labels appearing in this exact sequence.
var headerLabels = []struct {
	label string
	get   func(ETLHeader) string
}{
	{"Glue job", func(h ETLHeader) string { return h.JobName }},
	{"desarrollado por", func(h ETLHeader) string { return h.DesarrolladoPor }},
	{"fecha creación", func(h ETLHeader) string { return h.FechaCreacion }},
	{"modificado por", func(h ETLHeader) string { return h.ModificadoPor }},
	{"fecha modificación", func(h ETLHeader) string { return h.FechaModificacion }},
	{"descripción", func(h ETLHeader) string { return h.Descripcion }},
}

// RenderHeader renders the six-field ETL header block as a sequence of "#"
// comment lines, one per field, with colons aligned to the longest label.
// The output is six newline-separated lines (no trailing newline) suitable
// for prepending to a generated `.py` source file.
func RenderHeader(h ETLHeader) string {
	lines := make([]string, 0, len(headerLabels))
	for _, entry := range headerLabels {
		lines = append(lines, renderHeaderLine(entry.label, entry.get(h)))
	}
	return strings.Join(lines, "\n")
}

// renderHeaderLine pads the "# <label>" prefix to headerLabelColumn runes then
// appends the " : " separator and the value. Padding is rune-based so the
// accented labels (creación, modificación, descripción) align correctly.
func renderHeaderLine(label, value string) string {
	prefix := "# " + label
	for utf8.RuneCountInString(prefix) < headerLabelColumn {
		prefix += " "
	}
	return prefix + " : " + value
}

// forbiddenHeaderPatterns are the authorship-attribution markers a generated
// ETL header MUST NOT contain. Each is matched case-insensitively as a
// substring against the rendered content. AI model/vendor names are listed
// explicitly rather than as a generic "ai" substring (which would false-fire
// on common words like "available" or "domain"). Deliberately ambiguous tokens
// that occur legitimately in ETL code (e.g. "cursor" — a SQL cursor) are
// excluded so the check stays meaningful.
var forbiddenHeaderPatterns = []string{
	"co-authored-by",
	"generated by",
	"auto-generated",
	"claude",
	"gpt",
	"chatgpt",
	"gemini",
	"copilot",
	"openai",
	"anthropic",
}

// ErrHeaderAttribution is the sentinel for ValidateHeader failures so callers
// can distinguish an authorship violation from a transport-level error.
var ErrHeaderAttribution = fmt.Errorf("etl: header contains AI attribution")

// ValidateHeader rejects AI-attribution markers in ETL header content. It
// returns a non-nil error (wrapping ErrHeaderAttribution) when the content
// contains "generated by", "Co-Authored-By", or a known AI model/vendor name
// (Claude, GPT, ChatGPT, Gemini, Copilot, OpenAI, Anthropic). The check is
// case-insensitive substring matching. A clean human-authored header returns
// nil.
func ValidateHeader(content string) error {
	lower := strings.ToLower(content)
	for _, pat := range forbiddenHeaderPatterns {
		if strings.Contains(lower, pat) {
			return fmt.Errorf("%w: forbidden marker %q", ErrHeaderAttribution, pat)
		}
	}
	return nil
}

// headerFieldByLabel maps a rendered label to a setter on ETLHeader. parseHeader
// uses it so the label vocabulary lives in exactly one place alongside the
// render table (headerLabels).
var headerFieldByLabel = map[string]func(*ETLHeader, string){
	"Glue job":           func(h *ETLHeader, v string) { h.JobName = v },
	"desarrollado por":   func(h *ETLHeader, v string) { h.DesarrolladoPor = v },
	"fecha creación":     func(h *ETLHeader, v string) { h.FechaCreacion = v },
	"modificado por":     func(h *ETLHeader, v string) { h.ModificadoPor = v },
	"fecha modificación": func(h *ETLHeader, v string) { h.FechaModificacion = v },
	"descripción":        func(h *ETLHeader, v string) { h.Descripcion = v },
}

// parseHeader extracts the six ETLHeader fields from a rendered header block.
// It is tolerant of surrounding whitespace and blank lines, and ignores
// non-"#" lines. A field is captured only when its "# <label> : <value>" line
// is present; the returned bool reports whether all six fields were found,
// which lets UpdateHeaderForModify decide whether a safe update is possible.
func parseHeader(block string) (ETLHeader, bool) {
	var h ETLHeader
	found := 0
	for _, line := range strings.Split(block, "\n") {
		s := strings.TrimSpace(line)
		if s == "" || !strings.HasPrefix(s, "#") {
			continue
		}
		idx := strings.Index(s, ":")
		if idx < 0 {
			continue
		}
		label := strings.TrimSpace(strings.TrimPrefix(s[:idx], "#"))
		value := strings.TrimSpace(s[idx+1:])
		if set, ok := headerFieldByLabel[label]; ok {
			set(&h, value)
			found++
		}
	}
	return h, found == len(headerLabels)
}

// UpdateHeaderForModify produces the updated header for a modification: it
// preserves the original author (desarrollado por) and creation date (fecha
// creación) while updating the modifier (modificado por) and modification
// date (fecha modificación) to the current human author and today's date.
// JobName and Descripcion are carried over from orig when present. If orig
// cannot be parsed as a complete six-field header, it is returned unchanged
// (non-destructive fallback) rather than emitting a partial header.
func UpdateHeaderForModify(orig, human, today string) string {
	h, ok := parseHeader(orig)
	if !ok {
		return orig
	}
	h.ModificadoPor = human
	h.FechaModificacion = today
	return RenderHeader(h)
}
